# Generated by Django 5.1.7 on 2025-04-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostDisciplina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_professor', models.CharField(max_length=100)),
                ('nome_disciplina', models.CharField(max_length=100)),
                ('img_professor', models.FileField(upload_to='professores/')),
            ],
        ),
    ]
