# Generated by Django 5.1.7 on 2025-04-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0002_postdisciplina_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMonitoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_monitoria', models.CharField(max_length=200)),
                ('descricao_monitoria', models.TextField()),
                ('img_monitoria', models.FileField(upload_to='monitorias/')),
            ],
        ),
    ]
