# Generated by Django 5.1.7 on 2025-04-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0003_postmonitoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=200)),
                ('arquivo', models.FileField(upload_to='documentacao/')),
            ],
        ),
        migrations.CreateModel(
            name='Extensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_extensao', models.CharField(max_length=200)),
                ('professor', models.CharField(max_length=200)),
                ('assunto', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PostNoticia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_noticia', models.CharField(max_length=200)),
                ('descricao_noticia', models.TextField()),
                ('img_noticia', models.FileField(upload_to='noticias/')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=200)),
                ('descricao_projeto', models.TextField()),
            ],
        ),
    ]
