# Generated by Django 5.2 on 2025-04-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0005_extensao_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(max_length=200)),
                ('link_evento', models.URLField(max_length=300)),
                ('data_evento', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
