# Generated by Django 5.2 on 2025-04-29 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0006_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentacao',
            name='tipo',
            field=models.CharField(choices=[('Requerimento', 'Requerimento'), ('Arquivo', 'Arquivo')], default='Arquivo', max_length=20),
        ),
    ]
