# Generated by Django 5.2.5 on 2025-09-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0007_documentacao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdisciplina',
            name='carga_horaria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postdisciplina',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postdisciplina',
            name='ementa',
            field=models.FileField(blank=True, null=True, upload_to='ementas/'),
        ),
        migrations.AddField(
            model_name='postdisciplina',
            name='tipo',
            field=models.CharField(choices=[('REG', 'Regular'), ('OPT', 'Optativa'), ('ELE', 'Eletiva'), ('COM', 'Complementar')], default='REG', max_length=3),
        ),
    ]
