# Generated by Django 5.2.6 on 2025-10-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0008_postdisciplina_carga_horaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacao',
            name='tipo',
            field=models.CharField(choices=[('Requerimento', 'Requerimento'), ('Arquivo', 'Arquivo'), ('Prouni', 'Prouni')], default='Arquivo', max_length=20),
        ),
    ]
