# Generated by Django 5.1.7 on 2025-10-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0008_postdisciplina_carga_horaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='descricao_ampliada',
            field=models.TextField(blank=True, help_text='Descrição detalhada do projeto', null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='equipe',
            field=models.TextField(blank=True, help_text='Membros da equipe e suas funções (um por linha)', null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='img_projeto',
            field=models.FileField(blank=True, null=True, upload_to='projetos/'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='periodo_desenvolvimento',
            field=models.CharField(blank=True, help_text='Ex: Março a Junho de 2025', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='repositorio_url',
            field=models.URLField(blank=True, help_text='Link do repositório GitHub', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='tecnologia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='tipo_parceria',
            field=models.CharField(blank=True, choices=[('Parceria com Alunos', 'Parceria com Alunos'), ('Coordenação', 'Coordenação'), ('Empresa', 'Empresa'), ('Outro', 'Outro')], max_length=50, null=True),
        ),
    ]
