# Generated by Django 5.1.7 on 2025-10-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0009_alter_documentacao_tipo'),
        ('ads_app', '0009_projeto_ano_projeto_descricao_ampliada_and_more'),
    ]

    operations = [
    ]
