# Generated by Django 5.2.6 on 2025-11-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0009_projeto_ano_projeto_descricao_ampliada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacao',
            name='tipo',
            field=models.CharField(choices=[('Requerimento', 'Requerimento'), ('Arquivo', 'Arquivo'), ('Prouni', 'Prouni')], default='Arquivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='postdisciplina',
            name='tipo',
            field=models.CharField(choices=[('OBR', 'Obrigatória'), ('NOB', 'Não obrigatória')], default='OBR', max_length=3),
        ),
    ]
