# Generated by Django 5.1.7 on 2025-11-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0010_merge_20251028_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacao',
            name='tipo',
            field=models.CharField(choices=[('Requerimento', 'Requerimento'), ('Arquivo', 'Arquivo'), ('Prouni', 'Prouni'), ('FIES', 'FIES')], default='Arquivo', max_length=20),
        ),
    ]
