# Generated by Django 5.1.7 on 2025-11-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0011_alter_documentacao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link do vídeo no YouTube', max_length=300, null=True),
        ),
    ]
